<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ls</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>name</key>
	<string>LoomScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.loomscript</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(//).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.loomscript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.loomscript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.loomscript</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.class.loomscript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.loomscript</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(import)\s+(.*?)((;)|$)</string>
			<key>name</key>
			<string>storage.type.import.loomscript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(package)\s+</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.loomscript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>([\w\.]+)?</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.package.loomscript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.package.loomscript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.loomscript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.loomscript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.loomscript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.loomscript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.loomscript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.loomscript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.loomscript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.loomscript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f)?\b</string>
			<key>name</key>
			<string>constant.numeric.loomscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|else|while|do|for|each|in|case|switch|do|default|with)\b</string>
			<key>name</key>
			<string>keyword.control.loomscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(try|catch|finally|throw)\b</string>
			<key>name</key>
			<string>keyword.control.catch-exception.loomscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(exit|return|break|continue)\b</string>
			<key>name</key>
			<string>keyword.control.end.loomscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(as|delete|new|is|typeof)\b</string>
			<key>name</key>
			<string>keyword.operator.loomscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\*|Null|void)\b</string>
			<key>name</key>
			<string>keyword.special-type.loomscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(dynamic|final|internal|native|override|private|protected|public|static)\b</string>
			<key>name</key>
			<string>storage.modifier.loomscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\.\.\.|class|const|extends|function|get|implements|interface|package|set|namespace|var)\b</string>
			<key>name</key>
			<string>storage.type.loomscript</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.loomscript</string>
	<key>uuid</key>
	<string>ea894348-665e-4eea-a116-fdab8ed097a4</string>
</dict>
</plist>
