<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ls</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>name</key>
	<string>LoomScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>import</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.import.loomscript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.loomscript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.declaration.loomscript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(package)\s+</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.loomscript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>([\w\.]+)?</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.package.loomscript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.package.loomscript</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.loomscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(//).*$\n?</string>
					<key>name</key>
					<string>comment.line.double-slash.loomscript</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.loomscript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.loomscript</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(true|false|null)\b</string>
					<key>name</key>
					<string>constant.language.loomscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f)?\b</string>
					<key>name</key>
					<string>constant.numeric.loomscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bas\b</string>
					<key>name</key>
					<string>keyword.cast.loomscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(if|else|while|do|for|each|in|case|switch|do|default|with|return)\b</string>
					<key>name</key>
					<string>keyword.control.loomscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(exit|return|break|continue)\b</string>
					<key>name</key>
					<string>keyword.control.end.loomscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(new)\b</string>
					<key>name</key>
					<string>keyword.control.new.loomscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\?|:</string>
					<key>name</key>
					<string>keyword.control.ternary.loomscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(\.\.\.|class|const|extends|function|get|implements|interface|package|set|namespace|var)\b</string>
					<key>name</key>
					<string>keyword.declaration.loomscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(delete|is|typeof)\b</string>
					<key>name</key>
					<string>keyword.operator.loomscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\-|\+|\*|\/|\~\/|%)</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.loomscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(=)</string>
					<key>name</key>
					<string>keyword.operator.assignment.loomscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(([+*/%-]|\~)=)</string>
					<key>name</key>
					<string>keyword.operator.assignment.arithmetic.loomscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(&lt;&lt;|&gt;&gt;&gt;?|~|\^|\||&amp;)</string>
					<key>name</key>
					<string>keyword.operator.bitwise.loomscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(===?|!==?|&lt;=?|&gt;=?)</string>
					<key>name</key>
					<string>keyword.operator.comparison.loomscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\-\-|\+\+)</string>
					<key>name</key>
					<string>keyword.operator.increment-decrement.loomscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(!|&amp;&amp;|\|\|)</string>
					<key>name</key>
					<string>keyword.operator.logical.loomscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((&amp;|\^|\||&lt;&lt;|&gt;&gt;&gt;?)=)</string>
					<key>name</key>
					<string>keyword.operator.assignment.bitwise.loomscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(\*|Null)\b</string>
					<key>name</key>
					<string>keyword.special-type.loomscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>;</string>
					<key>name</key>
					<string>punctuation.terminator.loomscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(dynamic|final|internal|native|override|private|protected|public|static)\b</string>
					<key>name</key>
					<string>storage.modifier.loomscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:void|bool|int)\b</string>
					<key>name</key>
					<string>storage.type.primitive.loomscript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(this|super)\b</string>
					<key>name</key>
					<string>variable.language.loomscript</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.loomscript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.loomscript</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.loomscript</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.loomscript</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.loomscript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.loomscript</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.loomscript</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.loomscript</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.loomscript</string>
	<key>uuid</key>
	<string>ea894348-665e-4eea-a116-fdab8ed097a4</string>
</dict>
</plist>
